[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 10
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"
    footer = 'Maintained by <a class="text-muted" href="https://github.com/marvelxcodes/">MarvelXCodes</a>'
